services:
  api:
    build: .
    container_name: brief-reun-api
    restart: always
    env_file: .env
    expose:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.brief-reun.rule=Host(`api.macfor.ag`)"
      - "traefik.http.routers.brief-reun.entrypoints=websecure"
      - "traefik.http.routers.brief-reun.tls.certresolver=mytlschallenge"
      - "traefik.http.services.brief-reun.loadbalancer.server.port=5000"
    volumes:
      - logs:/var/log/brief-reun
    networks:
      - web

volumes:
  logs:

networks:
  web:
    external: true
    name: root_default
